<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>DeathbulgeArchipelagoClient</AssemblyName>
		<Product>Deathbulge Archipelago Client plugin</Product>
		<Version>1.0.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>DeathbulgeArchipelagoClient</RootNamespace>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PluginOutputDir>$(GamePath)\BepInEx\plugins\DeathbulgeArchipelagoClient</PluginOutputDir>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.1" />
		<PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
		<PackageReference Include="BepInEx.Core" Version="5.*" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="$(GamePath)\deathbulge_Data\Managed\*.dll"
				   Exclude="$(GamePath)\deathbulge_Data\Managed\mscorlib.dll;$(GamePath)\deathbulge_Data\Managed\netstandard.dll;$(GamePath)\deathbulge_Data\Managed\System*.dll"
				   Private="false" />
	</ItemGroup>

	<ItemGroup>
		<ResourceFiles Include="$(ProjectDir)resources\**\*.*" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<MakeDir Directories="$(PluginOutputDir)" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PluginOutputDir)" />
		<Copy SourceFiles="$(TargetDir)Archipelago.MultiClient.Net.dll" DestinationFolder="$(PluginOutputDir)" />
		<Copy SourceFiles="@(ResourceFiles)" DestinationFolder="$(PluginOutputDir)\resources\%(RecursiveDir)" />
	</Target>

</Project>
